name: drosi_mobile
description: تطبيق دروسي — متصل بموقع دروسي (Next.js API)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  uuid: ^4.5.1
  connectivity_plus: ^6.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
